import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(){
  return (
    <html lang="es">
      <body>
      <h1 className="text-3xl font-bold red-500">Ravenous</h1>
      </body>
    </html>
  );
}
