import type { Metadata } from "next";
import "./globals.css";
import SearchBar from "../components/SearchBar/SearchBar";
import BusinessList from "../components/BusinessList/BusinessList";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(){
  return (
    <html lang="es">
      <body suppressHydrationWarning>
        <h1 className="bg-[#C49847] py-5 text-white text-3xl font-bold text-center">Ravenous</h1>
      <SearchBar />
      <BusinessList />
      </body>
    </html>
  );
}